### ISSUE TITLE
老哥，继续更新下中文的代码的解析啊，感谢感谢感谢

### ISSUE THREAD

**Issue by icenaive** [QiujieDong/MeshCNN_COPY#1]
@QiujieDong

**Comment by QiujieDong** [comment]
志同道合的朋友：您好！

首先，非常感谢您对此repository的关注，由于学习调整与时间关系，此代码的中文注释暂时没有时间更新，非常抱歉。
如果您感兴趣可以看一下[kaolin](https://github.com/QiujieDong/kaolin-0.1_Fork)中对MeshCNN的实现。

**Comment by icenaive** [comment]
> 志同道合的朋友：您好！
> 
> 首先，非常感谢您对此repository的关注，由于学习调整与时间关系，此代码的中文注释暂时没有时间更新，非常抱歉。
> 如果您感兴趣可以看一下[kaolin](https://github.com/QiujieDong/kaolin-0.1_Fork)中对MeshCNN的实现。

感谢您的回复，我回去看一下[kaolin](https://github.com/QiujieDong/kaolin-0.1_Fork)中的实现的，也希望你有时间和机会的话可以继续这个工作，谢谢。
